---
title: "Clinical dashboard"
author: "dECMT"
date: "`r Sys.Date()`"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---


```{r copyright notice}
 # 
 # This file is part of the clinical dashboard distribution (https://github.com/digital-ECMT/clinical_dashboard).
 # Copyright (C) 2022 digital ECMT
 # 
 # This program is free software: you can redistribute it and/or modify  
 # it under the terms of the GNU General Public License as published by  
 # the Free Software Foundation, version 3 or later.
 #
 # This program is distributed in the hope that it will be useful, but 
 # WITHOUT ANY WARRANTY; without even the implied warranty of 
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 # General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License 
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
 #

```

```{r setup, include=FALSE}
require(flexdashboard)    ## MIT
require(dplyr)            ## MIT
require(DT)               ## GPL-3
require(ggplot2)          ## MIT
require(reshape2)         ## MIT
require(shinyWidgets)     ## GPL-3
require(lubridate)        ## GPL-2|3
# require(data.table)       ## MPL2

## clean up
rm(list=ls())

##create a custom palette based on dECMT branding
dECMTpalette <- c(rgb(red=0, green=137, blue=174, maxColorValue = 255), 
                  rgb(red=208, green=134, blue=146, maxColorValue = 255),
                  rgb(red=237, green=154, blue=75, maxColorValue = 255),
                  rgb(red=174, green=190, blue=6, maxColorValue = 255),
                  rgb(red=0, green=105, blue=145, maxColorValue = 255), 
                  rgb(red=197, green=74, blue=117, maxColorValue = 255),
                  rgb(red=229, green=113, blue=67, maxColorValue = 255),
                  rgb(red=119, green=167, blue=40, maxColorValue = 255),
                  rgb(red=113, green=121, blue=126, maxColorValue = 255),
                  rgb(red=0, green=0, blue=0, maxColorValue = 255),
                  rgb(red=242, green=222, blue=3, maxColorValue = 255),
                  rgb(red=146, green=68, blue=168, maxColorValue = 255),
                  rgb(red=108, green=200, blue=93, maxColorValue = 255),
                  rgb(red=254, green=240, blue=0, maxColorValue = 255),
                  rgb(red=105, green=25, blue=122, maxColorValue = 255),
                  rgb(red=35, green=99, blue=32, maxColorValue = 255))

```

```{r read and process demographics, warning=FALSE}
demographics_filepath <- paste0(getwd(), "/DEMOGRAPHICS.csv")

demographics <- read.csv(file = demographics_filepath, stringsAsFactors = FALSE, header = TRUE, na.strings = "NA")
# demographics <- data.table::fread(file = demographics_filepath, stringsAsFactors = FALSE, header = TRUE, na.strings = "NA")

## drop any rows with missing values
demographics <- demographics[complete.cases(demographics), ]

## drop any redundant rows
demographics <- unique(demographics)

## detect variable type... 
demographics$VARIABLE_TYPE <- NA
## first try and convert to numeric (anything other than number gives NA)
demographics$VARIABLE_TYPE[!is.na(as.numeric(demographics$VARIABLE_VALUE))] <- "NUMERIC"
## try and parse to date  
demographics$VARIABLE_TYPE[!is.na(lubridate::ymd(demographics$VARIABLE_VALUE))] <- "DATE"
## try and convert to logical
demographics$VARIABLE_TYPE[!is.na(as.logical(demographics$VARIABLE_VALUE))] <- "LOGICAL"
## if none of the above, assume character
demographics$VARIABLE_TYPE[is.na(demographics$VARIABLE_TYPE)] <- "CHARACTER"

## cast to wide format 
demographics_wide <- reshape2::dcast(data = demographics, formula = SUBJECT_ID ~ VARIABLE_NAME, value.var = "VARIABLE_VALUE")
demographics_wide$DOB <- lubridate::ymd(demographics_wide$DOB)

## loop through each column in demographics wide table and format according to corresponding VARIABLE_TYPE value... 
for(i in 2:ncol(demographics_wide)) {
  column_name = names(demographics_wide)[i]
  column_type = unique(demographics$VARIABLE_TYPE[demographics$VARIABLE_NAME == column_name])

  if(column_type == "DATE") {
    demographics_wide[ , i] <- lubridate::ymd(demographics_wide[ , i])
    next
  }
  if(column_type == "NUMERIC") {
    demographics_wide[ , i] <- as.numeric(demographics_wide[ , i])
    next
  }
  
  else {demographics_wide[ , i] <- factor(demographics_wide[ , i])
    next}
}


## store names of variables to use as stratifiers
stratifier_names <- unique(demographics$VARIABLE_NAME[demographics$VARIABLE_TYPE == "CHARACTER"])

```
   
```{r read and process events, warning=FALSE}
events_filepath <- paste0(getwd(), "/EVENTS.csv")

events <- read.csv(file = events_filepath, stringsAsFactors = FALSE, header = TRUE, na.strings = "NA")
# events <- data.table::fread(file = events_filepath, stringsAsFactors = FALSE, header = TRUE, na.strings = "NA")

## drop any rows with missing values
events <- events[complete.cases(events), ]

## drop any redundant rows
events <- unique(events)

## convert EVENT_DATETIME to datetime format
events$EVENT_DATETIME <- lubridate::as_datetime(events$EVENT_DATETIME)

## cast to wide format 
# as there may be >1 of a given event type, just get the event witht the earliest datetime value
events_wide <- events %>%
  group_by(SUBJECT_ID, EVENT_NAME) %>%
  arrange(EVENT_DATETIME) %>%
  slice_head(n = 1) %>%         ## just keep first of each event type
  arrange(SUBJECT_ID, EVENT_DATETIME) %>%       ## reorder again so when cast wide, columns are in chronological order
  as.data.frame() 

## work out the factor order for different event types (so we can reorder columns later when we cast to wide)
event_order <- events_wide %>%
    group_by(EVENT_NAME) %>%
    summarise(
        mean_datetime = mean(EVENT_DATETIME)
    ) %>%
    arrange(mean_datetime) %>%
    as.data.frame()

# cast wide
events_wide <- reshape2::dcast(data = events_wide, formula = SUBJECT_ID ~ factor(EVENT_NAME, levels = event_order$EVENT_NAME), value.var = "EVENT_DATETIME")

# convert the wide columns to date format
## for simplicity in wide version, we will just use date, not datetime
## loop through each column in demographics wide table and format according to corresponding VARIABLE_TYPE value...
for(i in 2:ncol(events_wide)) {
    events_wide[ , i] <- lubridate::as_datetime(events_wide[ , i])  ## convert to datetime first
    events_wide[ , i] <- lubridate::as_date(events_wide[ , i])  ## then just keep the date
}

## store a set of event names to populate filters in UI later...
event_names <- unique(event_order$EVENT_NAME)

```
  
```{r join demographics_wide to events_wide}
demographics_wide <- merge(x=demographics_wide, by.x = "SUBJECT_ID", all.x = TRUE, y=events_wide, by.y = "SUBJECT_ID", all.y = FALSE)

```

```{r read and process measurements, warning=FALSE}
measurements_filepath <- paste0(getwd(), "/MEASUREMENTS.csv")

measurements <- read.csv(file = measurements_filepath, stringsAsFactors = FALSE, header = TRUE, na.strings = "NA")
# measurements <- data.table::fread(file = measurements_filepath, stringsAsFactors = FALSE, header = TRUE, na.strings = "NA")

## drop any rows with missing values
measurements <- measurements[!is.na(measurements$MEASUREMENT_VALUE), ]

## drop any redundant rows
measurements <- unique(measurements)

## convert MEASUREMENT_DATETIME to datetime format
measurements$MEASUREMENT_DATETIME <- lubridate::as_datetime(measurements$MEASUREMENT_DATETIME)

measurements$VARIABLE_TYPE <- NA
for(i in 1:length(unique(measurements$MEASUREMENT_NAME))) {
  measurement_name <- unique(measurements$MEASUREMENT_NAME)[i]
  values <- unique(measurements$MEASUREMENT_VALUE[measurements$MEASUREMENT_NAME == measurement_name])
  ## test for logical first, since 0 and 1 can be numeric, but likely to be logical if no other numbers
  if(length(setdiff(values, c(0,1)))==0) {
    measurements$VARIABLE_TYPE[measurements$MEASUREMENT_NAME == measurement_name] <- "LOGICAL"
    next
  }
  if(!anyNA(as.logical(values))) {
    measurements$VARIABLE_TYPE[measurements$MEASUREMENT_NAME == measurement_name] <- "LOGICAL"
    next
  }
  ## test for numeric
  if(!anyNA(as.numeric(values))) {
    measurements$VARIABLE_TYPE[measurements$MEASUREMENT_NAME == measurement_name] <- "NUMERIC"
    next
  } else {
    ## else assume type is character
    measurements$VARIABLE_TYPE[measurements$MEASUREMENT_NAME == measurement_name] <- "CHARACTER"
  }
}

## get a vector of measurement names to use later
measurement_names <- unique(measurements$MEASUREMENT_NAME)
numeric_measurement_names <- unique(measurements$MEASUREMENT_NAME[measurements$VARIABLE_TYPE == "NUMERIC"])
```
  
```{r join measurements to demographics_wide}
measurements <- merge(x=demographics_wide, by.x="SUBJECT_ID", all.x=FALSE, y=measurements, by.y = "SUBJECT_ID", all.y = FALSE)

```

```{r calculate daily mean measurements, message=FALSE}
## calculate daily mean values for all numeric variables
dailyMean_measurements <- measurements %>%
    dplyr::filter(VARIABLE_TYPE == "NUMERIC") %>%
    group_by(SUBJECT_ID, MEASUREMENT_NAME, DATE= lubridate::as_date(MEASUREMENT_DATETIME)) %>%
    summarise(daily_mean = mean(as.numeric(MEASUREMENT_VALUE))) %>%
    reshape2::dcast(SUBJECT_ID + DATE ~ MEASUREMENT_NAME, value.var = "daily_mean")

dailyMean_measurements <- merge(x=demographics_wide, by.x="SUBJECT_ID", all.x=FALSE, y=dailyMean_measurements, by.y = "SUBJECT_ID", all.y = FALSE)

```

```{r specify colour palette for low and high values}
# make palette a named vector, with names matching factor levels, in order to control which color gets matched to what
pal <- c("LOW" = "blue","NORMAL" = "green","HIGH" = "red" )

```

Row {.tabset}
-----------------------------------------------------------------------  
   
### Population  
  
```{r reactive demographics table}

# create table with filters
output$populationTable = DT::renderDT(demographics_wide,
             filter = "top",
             options = list(pageLength = 25, autoWidth = TRUE)
        )

# render table
DT::dataTableOutput('populationTable')

# Reactive function to which rows are selected
sel <- reactive({ 
    input$populationTable_rows_all
})

# reactive function to hold IDs of patients in filtered list
selected_patients <- reactive({
  indices <- input$populationTable_rows_all
  subject_ids <- demographics_wide$SUBJECT_ID[indices]
  print(paste0("Selected patients: ", paste(subject_ids, collapse = ", ")))
  return(subject_ids)
})
renderText(selected_patients())

```

### Line plot  

```{r line plot}

measurements_lineplot <- reactive({
  ## geom_ribbon per group
  measurements %>%
    dplyr::filter(SUBJECT_ID %in% selected_patients()) %>%
    dplyr::filter(MEASUREMENT_NAME == input$lineplotVariable) %>%
    dplyr::mutate(timediff = round(difftime(MEASUREMENT_DATETIME, get(input$lineplotBaseline), unit="days"), digits = 0)) %>%
    dplyr::mutate(MEASUREMENT_VALUE = as.numeric(MEASUREMENT_VALUE)) %>%
    ggplot(aes(x=timediff, y=MEASUREMENT_VALUE, group=get(input$lineplotStratifier), color = get(input$lineplotStratifier))) +
        stat_summary(geom="ribbon", fun.data = "mean_se", aes(fill=get(input$lineplotStratifier)), alpha=0.3, show.legend = c(color = FALSE, fill = TRUE)) +
        geom_vline(xintercept=0) +
        # geom_smooth(aes(group=get(input$lineplotStratifier))) +
        scale_color_manual(values = dECMTpalette) +
        labs(title = paste0(input$lineplotVariable, " over time according to ", input$lineplotStratifier), x=paste0("Days since ", input$lineplotBaseline), y =input$lineplotVariable , fill = input$lineplotStratifier, color = input$lineplotStratifier)
  
})

output$lineplot <- renderPlot({
  measurements_lineplot()
})

## display on page
fillCol(height = 600, flex = c(NA, 1),
  inputPanel(
    selectInput(inputId = "lineplotBaseline", label="Select baseline event:", choices = event_names, selected = event_names[1], multiple = FALSE,  selectize = TRUE, width = NULL, size = NULL),
    selectInput(inputId = "lineplotVariable", label="Select measurement:", choices = numeric_measurement_names, selected = numeric_measurement_names[1], multiple = FALSE,  selectize = TRUE, width = NULL, size = NULL),
    selectInput(inputId = "lineplotStratifier", label="Select stratifier:", choices = stratifier_names, selected = stratifier_names[1], multiple = FALSE,  selectize = TRUE, width = NULL, size = NULL)
    ),
  plotOutput("lineplot", height = "100%")
)

```

### Violin plot  
  
```{r violin plot}

reactiveViolinPlot <- reactive({
   demographics_wide %>%
    dplyr::filter(SUBJECT_ID %in% selected_patients()) %>%
    dplyr::mutate(timediff = round(difftime(time2 = get(input$violinplotFrom), time1 = get(input$violinplotTo), unit="days"), digits = 0)) %>%
    ggplot(aes(x=get(input$violinplotStratifier), y=timediff, fill=get(input$violinplotStratifier))) +
      geom_violin(alpha=0.3, scale = "count") +
      geom_jitter(alpha=0.5,size = 5, width = 0.1, height = 0) +
      scale_color_manual(values = dECMTpalette) +
      labs(title = paste0("Time from ", input$violinplotFrom, " to ", input$violinplotTo, " according to ", input$violinplotStratifier), x=input$violinplotStratifier, y="Time, days", fill = input$violinplotStratifier)
   
})

output$violinPlot <- renderPlot({
  reactiveViolinPlot()
})

## display on page
fillCol(height = 600, flex = c(NA, 1),
  inputPanel(
    selectInput(inputId = "violinplotFrom", label="From:", choices = event_names, selected = event_names[1], multiple = FALSE,  selectize = TRUE, width = NULL, size = NULL),
    selectInput(inputId = "violinplotTo", label="To:", choices = event_names, selected = event_names[2], multiple = FALSE,  selectize = TRUE, width = NULL, size = NULL),
    
    selectInput(inputId = "violinplotStratifier", label="Select stratifier:", choices = stratifier_names, selected = stratifier_names[1], multiple = FALSE,  selectize = TRUE, width = NULL, size = NULL)
    ),  
  plotOutput("violinPlot", height = "100%")
)

```

### Time to event plot
  
```{r time to event plot}

reactiveTTEPlot <- reactive({
  demographics_wide %>%
    dplyr::filter(SUBJECT_ID %in% selected_patients()) %>%
    dplyr::group_by(get(input$TTEplotStratifier)) %>%
    mutate(day = round(difftime(time2 = get(input$TTEplotFrom), time1 = get(input$TTEplotTo), unit="days"), digits = 0)) %>%
    arrange(day) %>%
    mutate(event_count = cumsum(!is.na(get(input$TTEplotTo)))) %>%
    mutate(group_total = length(unique(SUBJECT_ID))) %>%
    mutate(cum_prop = round(event_count/group_total, digits = 3)) %>%
    ggplot(aes(x=day, y=cum_prop, color=get(input$TTEplotStratifier))) +
        geom_step() +
        expand_limits(x=0, y=c(0,1)) +
        scale_color_manual(values = dECMTpalette) +
        labs(title = paste0("Time from ", input$TTEplotFrom, " to ", input$TTEplotTo, " events according to ", input$TTEplotStratifier), x=paste0("Days since", input$TTEplotFrom), y="Cumulative proportion with event", color = input$TTEplotStratifier)
        # labs(title = "title", x="Days since (baseline)", y="Proportion with () event", fill = "GENDER", color = "GENDER") 
   
})

output$ttePlot <- renderPlot({
  reactiveTTEPlot()
})

## display on page
fillCol(height = 600, flex = c(NA, 1),
  inputPanel(
    selectInput(inputId = "TTEplotFrom", label="From:", choices = event_names, selected = event_names[1], multiple = FALSE,  selectize = TRUE, width = NULL, size = NULL),
    selectInput(inputId = "TTEplotTo", label="To:", choices = event_names, selected = event_names[2], multiple = FALSE,  selectize = TRUE, width = NULL, size = NULL),
    
    selectInput(inputId = "TTEplotStratifier", label="Select stratifier:", choices = stratifier_names, selected = stratifier_names[1], multiple = FALSE,  selectize = TRUE, width = NULL, size = NULL)
    ),  
  plotOutput("ttePlot", height = "100%")
)
```

### Heat map  
  
```{r heatmap}

## create a reactive slider that will amend min, max, range based on selected parameter
output$normal_range_slider <- renderUI({
   sliderInput("normal_range", 
               label = "Normal range:", 
               min = min(as.numeric(measurements$MEASUREMENT_VALUE[measurements$MEASUREMENT_NAME==input$heatMapVariable])),
               max = max(as.numeric(measurements$MEASUREMENT_VALUE[measurements$MEASUREMENT_NAME==input$heatMapVariable])),
               value = c(quantile(as.numeric(measurements$MEASUREMENT_VALUE[measurements$MEASUREMENT_NAME==input$heatMapVariable]))[2],
                         quantile(as.numeric(measurements$MEASUREMENT_VALUE[measurements$MEASUREMENT_NAME==input$heatMapVariable]))[4]
                         )
   )
})


measurements_heatmap <- reactive({
  # measurements %>%
  #   dplyr::filter(SUBJECT_ID %in% selected_patients()) %>%
  #   dplyr::filter(MEASUREMENT_NAME == input$heatMapVariable) %>%
  #   ggplot(aes(x=SUBJECT_ID, y=difftime(MEASUREMENT_DATETIME, get(input$heatmapBaseline), unit="days"))) +
  #     geom_tile(aes(colour=as.numeric(MEASUREMENT_VALUE))) +
  #     geom_hline(yintercept=0, color="black") +
  #     coord_flip() +
  #     labs(title = paste0(input$heatMapVariable ," versus ", input$heatmapBaseline), x="Subject ID", y =paste0("Days since ", input$heatmapBaseline) , colour = input$heatMapVariable) +
  #     guides(alpha="none") +
  #     binned_scale(aesthetics = "color",
  #                scale_name = "stepsn", 
  #                palette = function(x) {pal},
  #                breaks = c( 0,input$normal_range[1], input$normal_range[2]),
  #                show.limits = TRUE, 
  #                guide = "colorsteps"
  #   ) +
  #   facet_grid( get(input$heatmapStratifier) ~., scales="free_y", space = "free_y") +
  #   theme(plot.title = element_text(size=12, face="bold", hjust=0.5),
  #         axis.text.y=element_blank(),
  #         panel.border = element_rect(color = "black", fill = NA, size = 0.5),
  #         strip.background = element_rect(color = "black", size = 0.5),
  #         strip.text.y =  element_text(angle=0))
  
  ## daily means instead... 
  dailyMean_measurements %>%
    dplyr::filter(SUBJECT_ID %in% selected_patients()) %>%
    ggplot(aes(x=SUBJECT_ID, y=difftime(get("DATE"), get(input$heatmapBaseline), unit="days"))) +
      geom_tile(aes(alpha=0.5, color="black", fill=as.numeric(get(input$heatMapVariable)))) +
      geom_hline(yintercept=0, color="black") +
      coord_flip() +
      labs(title = paste0(input$heatMapVariable ," versus ", input$heatmapBaseline), x="Subject ID", y =paste0("Days since ", input$heatmapBaseline) , fill = input$heatMapVariable) +
      guides(alpha="none", color="none") +
      binned_scale(aesthetics = "fill",
                 scale_name = "stepsn", 
                 palette = function(x) {pal},
                 breaks = c( 0,input$normal_range[1], input$normal_range[2]),
                 show.limits = TRUE, 
                 guide = "colorsteps"
    ) +
      facet_grid( get(input$heatmapStratifier) ~., scales="free_y", space = "free_y") +
      theme(plot.title = element_text(size=12, face="bold", hjust=0.5),
          axis.text.y=element_blank(),
          panel.border = element_rect(color = "black", fill = NA, size = 0.5),
          strip.background = element_rect(color = "black", size = 0.5),
          strip.text.y =  element_text(angle=0))
  
})
  
output$heatmap_plot <- renderPlot({
  measurements_heatmap()
})

## display on page
fillCol(height = 600, flex = c(NA, 1),
  inputPanel(
    selectInput(inputId = "heatmapBaseline", label="Select baseline event:", choices = event_names, selected = event_names[1], multiple = FALSE,  selectize = TRUE, width = NULL, size = NULL),
    selectInput(inputId = "heatMapVariable", label="Select measurement:", choices = numeric_measurement_names, selected = numeric_measurement_names[1], multiple = FALSE,  selectize = TRUE, width = NULL, size = NULL),
    selectInput(inputId = "heatmapStratifier", label="Select stratifier:", choices = stratifier_names, selected = stratifier_names[1], multiple = FALSE,  selectize = TRUE, width = NULL, size = NULL),
    uiOutput("normal_range_slider") ## display the reactive slider

    ),
  plotOutput("heatmap_plot", height = "100%")
)

```
   
### x-y plot  
  
```{r xy plot}

## reactive plot
reactiveXYPlot <- reactive({
  dailyMean_measurements %>%
  dplyr::mutate(day = round(difftime(time2 = get(input$xyPlot_baseline), time1 = DATE, unit="days"), digits = 0)) %>%
  dplyr::filter(as.numeric(day) %in% (input$xyPlot_window[1]:input$xyPlot_window[2])) %>%
  ggplot(aes(x=get(input$xyPlot_x), y=get(input$xyPlot_y), group=get(input$xyPlot_baseline), color=get(input$xyPlotStratifier))) +
    geom_point(alpha=0.3,size = 5) +
    # geom_smooth(aes(group=get(input$xyPlotStratifier))) +
    scale_color_manual(values = dECMTpalette) +
    labs(title = paste0(input$xyPlot_x, " vs ", input$xyPlot_y, " (mean per day per subject) over ",input$xyPlot_window[2] ," day window after ", input$xyPlot_baseline), x=input$xyPlot_x, y=input$xyPlot_y, fill = input$xyPlotStratifier, color = input$xyPlotStratifier)
  
})

output$XYPlot <- renderPlot({
  reactiveXYPlot()
})

## display on page
fillCol(height = 600, flex = c(NA, 1),
  inputPanel(
    selectInput(inputId = "xyPlot_x", label="Select x axis:", choices = numeric_measurement_names, selected = numeric_measurement_names[1], multiple = FALSE,  selectize = TRUE, width = NULL, size = NULL),
    selectInput(inputId = "xyPlot_y", label="Select y axis:", choices = numeric_measurement_names, selected = numeric_measurement_names[2], multiple = FALSE,  selectize = TRUE, width = NULL, size = NULL),
    selectInput(inputId = "xyPlot_baseline", label="Select baseline:", choices = event_names, selected = event_names[1], multiple = FALSE,  selectize = TRUE, width = NULL, size = NULL),
    sliderInput("xyPlot_window", 
               label = "Time window after baseline:", 
               min = 0,
               max = 30,
               value = c(0,7)),
    selectInput(inputId = "xyPlotStratifier", label="Select stratifier:", choices = stratifier_names, selected = stratifier_names[1], multiple = FALSE,  selectize = TRUE, width = NULL, size = NULL)
    ),  
  plotOutput("XYPlot", height = "100%")
)

```
   
   
   
   
   