/*
 * Copyright 2021 The University of Manchester
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.acuity.va.security.acl.domain;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.springframework.util.ClassUtils;
import org.springframework.util.StringUtils;

/**
 * Simple Object representing an object entity identity in the spring security acl tables.
 *
 * This represents the MAP_STUDY_RULE acuity table.
 *
 * @author Glen
 */
public abstract class AbstractClinicalStudy extends AcuityObjectIdentityImpl {

    /**
     * Drug Programme of study.
     * <p>
     * For filtering on client.
     * <p>
     */
    protected String drugProgramme;
    protected String code;

    public AbstractClinicalStudy() {
        Class<?> typeClass = ClassUtils.getUserClass(this.getClass());
        type = typeClass.getName();
        supertype = typeClass.getName();
    }

    public AbstractClinicalStudy(Long identifier) {
        this();
        this.id = identifier;
    }

    public AbstractClinicalStudy(String code, String name) {
        this();
        this.id = generateId(code);
        this.name = name;
        this.code = code;
    }

    public AbstractClinicalStudy(Long identifier, String code, String name) {
        this(identifier);
        this.name = name;
        this.code = code;
    }

    public AbstractClinicalStudy(Long identifier, String code, String name, Integer mask) {
        this(identifier, code, name);
        this.permissionMask = mask;
    }

    public AbstractClinicalStudy(String code, String name, Integer mask) {
        this(code, name);
        this.permissionMask = mask;
    }

    public String getDrugProgramme() {
        return drugProgramme;
    }
    
    public String getCode() {
        return code;
    }

    /**
     * Gets the class of the parent drug programme
     */
    @JsonIgnore
    public abstract Class getDrugProgrammeClass();

    /**
     * Gets the class name of the parent drug programme
     */
    @JsonIgnore
    public abstract String getDrugProgrammeClassString();

    public void setDrugProgramme(String drugProgramme) {
        this.drugProgramme = drugProgramme;
    }
    
    @Override
    public boolean isAutoGeneratedId() {
        if (StringUtils.isEmpty(code)) {
            return false;
        } else {
            return generateId(code).equals(id);
        }
    }

    @Override
    public boolean isLockdown() {
        return false;
    }

    @Override
    public String toString() {
        return "ClinicalStudy{id=" + id + ", code=" + code + ", name=" + name + ", type=" + type + ", drugProgramme=" + drugProgramme + "}";
    }
}
