/*
 * Copyright 2021 The University of Manchester
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.acuity.va.security.acl.domain;

import com.acuity.va.security.acl.domain.AcuityObjectIdentityImpl.Origin;
import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import org.springframework.security.acls.model.ObjectIdentity;

/**
 *
 * @author glen
 */
@JsonTypeInfo(
    use = JsonTypeInfo.Id.CLASS,
    property = "type",
    include = JsonTypeInfo.As.EXISTING_PROPERTY)
@JsonSubTypes({
    @JsonSubTypes.Type(value = AcuityDataset.class, name = "com.acuity.va.security.acl.domain.AcuityDataset"),
    @JsonSubTypes.Type(value = DetectDataset.class, name = "com.acuity.va.security.acl.domain.DetectDataset"),
    @JsonSubTypes.Type(value = DrugProgramme.class, name = "com.acuity.va.security.acl.domain.DrugProgramme"),
    @JsonSubTypes.Type(value = ClinicalStudy.class, name = "com.acuity.va.security.acl.domain.ClinicalStudy")
})
public interface AcuityObjectIdentity extends ObjectIdentity {

    /*
     * Name of the Drug Progamme, Study, Acuity Instance
     */
    String getName();

    /*
     * Primary key of the Drug Progamme, Study, Acuity Instance
     */
    Long getId();

    /*
     * Only put into stop identifier being serialised
     */
    @JsonIgnore
    @Override
    Serializable getIdentifier();

    /*
     * Checks if this of a Drug Programme type
     * 
     * Using this instead of is to stop typescript-generator-maven-plugin generating loads of attributes
     */
    @JsonIgnore
    boolean thisDrugProgrammeType();

    /*
     * Checks if this of a Clinical Study type
     */
    @JsonIgnore
    boolean thisClinicalStudyType();

    /*
     * Checks if this of a Dataset type
     */
    @JsonIgnore
    boolean thisDatasetType();

    /*
     * Checks if this acuity type
     */
    @JsonIgnore
    boolean thisAcuityType();

    /*
     * Checks if this acuity type
     */
    @JsonIgnore
    boolean thisDetectType();

    /*
     * Returns the short name, either acuity or detect
     */
    String getShortNameByType();

    /*
     * Clones the object, resetting
     */
    AcuityObjectIdentity cloneAndReset();

    /*
     * returns if the ROI has an auto genereted id
     */
    boolean isAutoGeneratedId();

    /*
     * returns super type of the class
     */
    String getSupertype();

    /*
     * which db does it come from
     */
    Origin getOrigin();
}
