/*
 * Copyright 2021 The University of Manchester
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.acuity.va.security.acl.domain;

/**
 * Simple Object representing an object entity identity in the spring security acl tables.
 *
 * This represents the MAP_PROJECT_RULE acuity table.
 *
 * @author Glen
 */
public class DrugProgramme extends AbstractDrugProgramme {

    public DrugProgramme() {
        super();
    }

    @Deprecated // dont use use for dp
    public DrugProgramme(Long id) {
        super(id, "Autogenerated name used for testing " + Math.random());
    }
    
    @Deprecated // dont use use for dp
    public DrugProgramme(Long id, String name) {
        super(id, name);
    }
    
    @Deprecated // dont use use for dp
    public DrugProgramme(Long id, String name, Integer mask) {
        super(id, name, mask);
    }
    
    public DrugProgramme(String name) {
        super(name);
    }

    public DrugProgramme(String name, Integer mask) {
        super(name, mask);
    }

    @Override
    public String toString() {
        return "DrugProgramme{id=" + id + ", name=" + name + ", type=" + type + "}";
    }
}
