/*
 * Copyright 2021 The University of Manchester
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

-- ACL schema sql used in H2

-- drop table acl_entry;
-- drop table acl_remote;
-- drop table acl_object_identity;
-- drop table acl_class;
-- drop table acl_sid;

-- 
create table acl_sid(
    id bigint generated by default as identity(start with 200) not null primary key,
    principal boolean not null,
    sid varchar_ignorecase(100) not null,
    constraint unique_uk_1 unique(sid,principal)
);

create table acl_remote (
    id NUMBER(38) NOT NULL PRIMARY KEY,
    name varchar(500) not null,
    base_url varchar(500) not null,
    enabled boolean not null
);

create table acl_class(
    id bigint generated by default as identity(start with 200) not null primary key,
    class varchar_ignorecase(100) not null,
    acl_remote_id NUMBER(38) NOT NULL,
    constraint unique_uk_2 unique(class),
    constraint FK_acl_remote_id foreign key (acl_remote_id) references acl_remote(ID)
);

create table acl_object_identity(
    id bigint generated by default as identity(start with 200) not null primary key,
    object_id_class bigint not null,
    object_id_identity bigint not null,
    parent_object bigint,
    owner_sid bigint,
    entries_inheriting boolean not null,
    constraint unique_uk_3 unique(object_id_class,object_id_identity),
    constraint foreign_fk_1 foreign key(parent_object) references acl_object_identity(id),
    constraint foreign_fk_2 foreign key(object_id_class) references acl_class(id),
    constraint foreign_fk_3 foreign key(owner_sid) references acl_sid(id)
);

create table acl_object (
    id bigint generated by default as identity(start with 200) not null primary key,
    name varchar_ignorecase(500) not null,
    acl_object_identity_id NUMBER(38) not null,
    module_type VARCHAR(100),
    default_vis VARCHAR(100),
    parent_drug_programme varchar(500),
    parent_study varchar(500),
    CONSTRAINT FK_acl_object_id foreign key (acl_object_identity_id) references acl_object_identity(ID) 
);

create table acl_entry(
    id bigint generated by default as identity(start with 200) not null primary key,
    acl_object_identity bigint not null,
    ace_order int not null,
    sid bigint not null,
    mask integer not null,
    granting boolean not null,
    audit_success boolean not null,
    audit_failure boolean not null,
    constraint unique_uk_4 unique(acl_object_identity,ace_order),
    constraint foreign_fk_4 foreign key(acl_object_identity) references acl_object_identity(id),
    constraint foreign_fk_5 foreign key(sid) references acl_sid(id)
);
