name: VA-Hub-CI
on:
  repository_dispatch:
    types: [va-security-update]
  push:
    branches:
      - master
  release:
    types: [ published,created,edited ]
jobs:
  push_to_registries:
    name: Create and push docker image to registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Configure Maven
        uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: |
            [{
                "id": "github",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
            },
            {
              "id": "github-packages",
              "username": "${{ github.actor }}",
              "password": "${{ secrets.GITHUB_TOKEN }}"
            },
            {
              "id": "ghcr.io",
              "username": "${{ github.actor }}",
              "password": "${{ secrets.GITHUB_TOKEN }}"
             }]
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy packages
        run: mvn clean deploy -P docker,webapp,github

