name: Test pull-request
on: pull_request
jobs:
  test_pull_request:
    name: Test for pull request
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Configure Maven
        uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: |
            [{
                "id": "github",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
            },
            {
              "id": "github-packages",
              "username": "${{ github.actor }}",
              "password": "${{ secrets.GITHUB_TOKEN }}"
            },
            {
              "id": "ghcr.io",
              "username": "${{ github.actor }}",
              "password": "${{ secrets.GITHUB_TOKEN }}"
             }]
      - name: Run tests
        run: mvn clean test -P github
